build:
 version: "1.O"
 
spring:
 config:
  active:
   on-profile: "prod"
   
accounts:
 message: "Welcome to easybank accounts related Production APIS"
 contactDetails:
  name: "babu - Teamlead"
  email: "babu@gmail.com"
      
