build:
 version: "2.O"
 
spring:
 config:
  active:
   on-profile: "qa"
   
accounts:
 message: "Welcome to easybank accounts related QAaaaaaaa APIS"
 contactDetails:
  name: "lucky - QA lead"
  email: "luckyqa@gmail.com"
      
